### ISSUE TITLE
Feature turn conditionals

### ISSUE THREAD

**Issue by Awia00** [Colonists-Game/Colonists#72]
Some conditionals are not on a single action but is required to happen during a turn, such as moving the thief if a 7 is rolled.
It can be implemented by adding a TurnConditions predicate on world that endTurn can check at the end.

**Comment by andersfischernielsen** [comment]
So this would be `turnConditions: TurnCondition[]` on `World`? 
I assume the signature of `TurnCondition` would be `(Result<World>) => boolean`?

**Comment by Awia00** [comment]
Yes that sounds right.

**Comment by andersfischernielsen** [comment]
59bb1bc helps with some of this.

**Comment by andersfischernielsen** [comment]
I propose: 

- Modifying ?shared/World.ts?` to have
```
{
...
turnConditions: TurnConditions[], 
...
}
```

where

`interface TurnConditions = 'rolledASeven' | 'shouldBuildTwoRoads'`

in case the player either rolled a seven or played a Road Building development card.

**Comment by andersfischernielsen** [comment]
We can't transfer objects with predicates back and forth to the client (due to serialisation), so the conditions would have to be value types

**Comment by andersfischernielsen** [comment]
`EndTurn` would then have to run reduce on the `TurnConditions[]` and return a `Result` whether the conditions held for the incoming `World`

**Comment by andersfischernielsen** [comment]
Implemented in #1209. I couldn't do it as simply as the comments above state, but managed to find a decent solution
